### ISSUE TITLE
"'NoneType' object is not subscriptable" error when trying to run ccs_find

### ISSUE THREAD

**Issue by agnesbrnb** [sangeeta97/ccs_find#1]
Hello,
I wanted to test your tool ccs_find, but I encountered some issues. 

I converted a raw file from a Waters mass spectrometer to mzML using msconvert (proteowizard). I have one version where I performed the standard conversion and another one for which I selected the ion mobility option.

I first tried to launch ccs_find on a VM with 8 GB RAM but it crashed with "memory allocation" error. Then, I tried on an Ubuntu server (190 GB RAM) with and without GUI and I got the following error for both mzML files:

>(ccs_find) abarnabe@unicorn:\~/Documents/ccs_find$ python processor.py -g my_config.ini
{\<my config file content\>}
Function run_all(<src.drift_time.Parse_MF object at 0x7fa013ecae50>,) {} Took 346.7534 seconds
Function formula_define(<src.drift_time.Parse_MF object at 0x7fa013ecae50>, ['[M]-', '-H']) {} Took 0.0044 seconds
Function rt_window_formula(<src.calculation.Calculation object at 0x7f9fcfd2a370>,) {} Took 0.0004 seconds
Function run_commandline(<src.Final object at 0x7fa019302eb0>,) {} Took 347.3011 seconds
Traceback (most recent call last):
  File "\~/Documents/ccs_find/processor.py", line 98, in <module>
    args = parse_arguments()
  File "\~/Documents/ccs_find/processor.py", line 79, in parse_arguments
    ccs_table["drift_time"] = ccs_table["drift_time"].map(lambda x: float(x)).map(lambda x: round(x, 3))
TypeError: 'NoneType' object is not subscriptable
>

Do you have any idea on how to solve this issue? Is it a conversion problem?

Thanks in advance for you help

**Comment by sangeeta97** [comment]
Hello,

Thanks for using the tool.

I would like to mention that this version of CCSfind is only able to address drift tube IM-MS data. It seems to be the elements(tags) are not found as per codes in the input mzml file. You can still able to download the file intermediate results from the gui version, just click on the download button, let me know if this address your question, also, I would like to keep config.ini unchanged as it enforces the beginner users to see the format of yaml file to be used.
